spring:
  config:
    import: optional:configserver:http://localhost:8086/
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicesRating

server:
  port: 8083





#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8084/eureka